### ISSUE TITLE
for branch https://github.com/project-bitmark/bitmark/tree/v0.9.3

### ISSUE THREAD

**Issue by ileathan** [project-bitmark/bitmark#14]
Using the latest version of Mac OS I got this error after `./autogen.sh && ./configure --with-boost-libdir=/usr/local/Cellar/boost/1.63.0/lib && make`

> net.cpp:1067:15: error: no matching function for call to 'upnpDiscover'
>     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
>               ^~~~~~~~~~~~
> /usr/local/include/miniupnpc/miniupnpc.h:62:1: note: candidate function not viable: requires 7 arguments, but 6 were provided
> upnpDiscover(int delay, const char * multicastif,
> ^
> 1 error generated. 
> 

So I opened my text editor and edited that line to `devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, 0, 0);`

After that edit the compile worked although I didn't actually go read the upnpDiscover code so I have no idea what I did.

**Comment by dbkeys** [comment]
Resolved with upgrade to new version of libminiupnp
