### ISSUE TITLE
getinfo missing helpful data

### ISSUE THREAD

**Issue by crackfoo** [project-bitmark/bitmark#46]
Hi, 

To be consistent  with all the other multi-algo coins could you add the missing fields:

pow_algo_id, pow_algo and difficulty

Example from ARG:

ARG scrypt
{
  "version": 4140300,
  "protocolversion": 1090000,
  "walletversion": 60000,
  "balance": 9.29367439,
  "blocks": 3138494,
  "timeoffset": -1,
  "connections": 19,
  "proxy": "",
  "pow_algo_id": 1,
  "pow_algo": "Scrypt",
  "difficulty": 2637127.305992147,
  "difficulty_sha256d": 2629485835.201973,
  "difficulty_scrypt": 2637127.305992147,
  "difficulty_lyra2re2": 200.2645212118318,
  "difficulty_groestl": 5973.255004714738,
  "difficulty_argon2d": 0.02092733630310869,
  "difficulty_yescrypt": 0.127252427184466,
  "testnet": false,
  "keypoololdest": 1527772795,
  "keypoolsize": 103,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}

The   "difficulty": value should always match what the pow_algo is.

**Comment by dbkeys** [comment]
Fixed in dev branch (for v0.9.7.1 release)
