### ISSUE TITLE
Not syncing from block 451098

### ISSUE THREAD

**Issue by sureshk1985** [project-bitmark/bitmark#49]
Hi,
The new version of Bitmark core V.0.9.7 is getting close while synchronizing the block 451098. What need to be done to fix this issue

Regards
Sureshkumar, K

**Comment by piratelinux** [comment]
451099 is the first cryptonight block (http://explorer.bitmark.co/?451120). There was a problem with the cryptonight hash implementation for Windows, but a new working binary has been confirmed, so we will release it soon.

**Comment by sureshk1985** [comment]
When can we expect the new binary with this fix

Regards
Sureshkumar, K

**Comment by dbkeys** [comment]
We are working on a solution to this problem. 
You may try to work around it by placing the bootstrap.dat file in your Bitmark data directory.

**Comment by sureshk1985** [comment]
We tried with bootstrap.dat file to bitmark data directory even. It is getting stopped at 451098. 

Regards
Sureshkumar, K

**Comment by dbkeys** [comment]
Please upgrade to Bitmark RC1-v0.9.7.1 version, now published here on Github. We believe this will solve the problem.

Best Regards,

db Keys

**Comment by dbkeys** [comment]
Standard CryptoNight Code 
bitmark-0.9.7.1-RC1-win64-setup.exe (4bdb6cd4035ae3b8f9cadbd4d36bd98f8d690cc422e30ae86f66db32bb74350e )
bitmark-0.9.7.1-RC1-win32-setup.exe  (4e5abccbe39793d9187ac551b59acd5c1cda1ddefa7c39e7780b572ee3e8b95a  )

**Comment by dbkeys** [comment]
Standard CryptoNight Code
bitmark-0.9.7.1-RC1-win64-setup.exe (4bdb6cd4035ae3b8f9cadbd4d36bd98f8d690cc422e30ae86f66db32bb74350e )
bitmark-0.9.7.1-RC1-win32-setup.exe  (4e5abccbe39793d9187ac551b59acd5c1cda1ddefa7c39e7780b572ee3e8b95a  )

**Comment by sureshk1985** [comment]
Thank you dbkeys.
