### ISSUE TITLE
Bitmark-Qt-HighSierra_0.9.7.1: can't sync blockchain

### ISSUE THREAD

**Issue by johnnytucker** [project-bitmark/bitmark#58]
Hi,

I'm running Bitmark-Qt-HighSierra_0.9.7.1-RC1.dmg and can't get my blockchain to sync.

My /Volumes/LaCie/AppSupport/Bitmark/debug.log file is full lines like the following:
2018-06-24 18:17:09 connect() to 127.0.0.1:9050 failed after select(): Connection refused (61)
2018-06-24 18:17:10 connect() to 127.0.0.1:9050 failed after select(): Connection refused (61)
...
2018-06-24 18:17:11 connect() to 127.0.0.1:9050 failed after select(): Connection refused (61)

Any idea what I can do to get passed this?  I had the same problem is the previous version.

Thanks,
  ~Johnny

**Comment by johnnytucker** [comment]
Hi,

I don't have the following on my MacBook:
1) bitmark.conf file
2) "~/Library/Application Support/Bitcoin" folder

I do have this file but it's binary (i.e. unreadable): "~/Library/Application Support/Bitmark/wallet.dat"

Should I create a bitmark.conf in some folder under "~/Library/Application Support/Bitmark"?

Also, I've attached a screenshot of my "Bitmark-Qt->Preferences->Network".


Thanks,
  ~Johnny
<img width="840" alt="screen shot 2018-06-24 at 4 01 48 pm" src="https://user-images.githubusercontent.com/842751/41823682-e4b3d76e-77c9-11e8-8ba5-eb9e40534a31.png">

**Comment by johnnytucker** [comment]
Hi,

I got it working by creating "~/Library/Application Support/Bitmark/bitmark.conf"

Thanks!

 ~Johnny

**Comment by dbkeys** [comment]
We should provide a model, commented bitmark.orig.conf which can act as an example template.
