### ISSUE TITLE
v0.9.7.0 bitmarkd issue

### ISSUE THREAD

**Issue by WonnieSim** [project-bitmark/bitmark#63]
When I downloaded and ran bitmarkd (v0.9.7.0), I ran into 
```
bitmarkd: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
```
Could I get some help on debugging this?

**Comment by dbkeys** [comment]
What operating system version are you running. For Ubuntu, try:

**Comment by WonnieSim** [comment]
I'm running on debian

**Comment by dbkeys** [comment]
It's likely the Debian (what version ? ) you have is using an earlier version of the Boost library than what our pre-compiled binary  calls for.  (We're compiling it on Ubuntu 16.04 LTS).
```dpkg -l | grep boost```

**Comment by WonnieSim** [comment]
It seems like it's the versions are at least 1.62.0.1 - is this older than Birmarkd's pre-compiled binary wants?
```
ii  libboost-all-dev                       1.62.0.1                       amd64        Boost C++ Libraries development files (ALL) (default version)
```

For the Debian - I'm using a [docker repo debian](https://hub.docker.com/_/debian/)(stable-20180625) since I'm building this image on docker container.

**Comment by dbkeys** [comment]
That seeme like a later version, but still incompatible. Are you compiling Btimark, or just trying to run the binary from the Release link ?

**Comment by WonnieSim** [comment]
Trying to run the binary from the Release link

**Comment by dbkeys** [comment]
Perhaps you can find the needed Boost 1.58 components (maybe an earlier Docker image ?) and place them manually where bitmarkd calls for them. For example, the 'ldd' command will reveal what & where:
```ldd bitmarkd
	linux-vdso.so.1 =>  (0x00007ffceb9ee000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f16646a3000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f166448b000)
	libboost_program_options.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0 (0x00007f166420d000)
	libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007f1663fe7000)
	libdb_cxx-4.8.so => /usr/lib/libdb_cxx-4.8.so (0x00007f1663c43000)
	libminiupnpc.so.10 => /usr/lib/x86_64-linux-gnu/libminiupnpc.so.10 (0x00007f1663a36000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f16637cd000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f1663389000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1663007000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1662cfe000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1662ae8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f16628cb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1662501000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f16622f9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f16620f5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1664e4c000)```
If you're system is missing a library wanted by bitmarkd, it will appear empty on the above list.

Compiling binaries for other distros, inlcuding Debian 8 & 9, is on our to-do list, after the release of v0.9.7.1
If you're inclined to compile a version for Debian, it would be helpful for the project and we would be grateful. You can find us on IRC or Slack.

**Comment by WonnieSim** [comment]
May I ask how you installed Boost 1.58? I can't find the version in apt-get anymore :( (I only see 1.62*)

**Comment by dbkeys** [comment]
The versions are usually chosen by the people making the distribution.  What version of Debian are you using ?  Maybe by using an earlier Debian version you can get it to work, but in that case, better to just use Ubuntu 16.04.

**Comment by dbkeys** [comment]
You're right, from what I can see, Debian never really used Boost 1.58. They choose whatever is current at the time they release a distribution, I suppose.

**Comment by WonnieSim** [comment]
Updated the base to Ubuntu 16.04 and it works perfectly. Thank you :))
