### ISSUE TITLE
Bitmark doesn't sync after block 518192

### ISSUE THREAD

**Issue by kr1z1s** [project-bitmark/bitmark#87]
I use the latest source code.

Error in logs

<img width="1422" alt="2018-09-12 09 36 38" src="https://user-images.githubusercontent.com/5347595/45406611-b5a64d00-b66f-11e8-9ef3-a3935d586440.png">

In block explorer - https://chainz.cryptoid.info/btm/   
block 518192

Linux cmd - 
    "version" : 90803,
    "protocolversion" : 70004,
    "walletversion" : 60000,
    "balance" : 43.67411264,
    "blocks" : 518192,
    "timeoffset" : 0,
    "connections" : 33,
    "proxy" : "",
    "pow_algo_id" : 1,
    "pow_algo" : "SHA256D",
    "difficulty" : 4550197735.87287235,
    "difficulty SCRYPT" : 4565238321.23421860,
    "difficulty SHA256D" : 4550197735.87287235,
    "difficulty YESCRYPT" : 395775.61542701,
    "difficulty ARGON2" : 57671.75850463,
    "difficulty X17" : 27722770.85589155,
    "difficulty LYRA2REv2" : 375112875.74920577,
    "difficulty EQUIHASH" : 390742.84964733,
    "difficulty CRYPTONIGHT" : 32616.68046951,
    "moneysupply" : 9615144.54067053,
    "testnet" : false,
    "keypoololdest" : 1536164182,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    "errors" : ""

I updated the sources, removed the blocks and again the same thing.

**Comment by dbkeys** [comment]
Please use Bitmark v0.9.7.2 (https://github.com/project-bitmark/bitmark/releases/tag/v0.9.7.2) for now.   Bitark v0.9.7.2 is the latest official release as of this post.
(Note: Version v0.9.8.3 was hardcoded to fork at height 518191, but issues were found with the code that require revision, so the fork (Fork #2) did not take place. )

**Comment by kr1z1s** [comment]
Good. You're right. But... Write then here - https://chainz.cryptoid.info/btm/ and here - https://poloniex.com/exchange/#btc_btm

**Comment by dbkeys** [comment]
Yes, I'm aware that  https://chainz.cryptoid.info/btm/  is on v0.9.8.3; we had advised them to update, which they did dutifully. I will ask cryptoid.info to please revert to v0.9.7.2.
I assume Poloniex freezes withdrawals / deposits out of an abundance of caution until it is clear which is the prevailing fork. In this case, I believe it is clear the functional version is v0.9.7.2; ( as no one is even mining the other version, and the block count is stuck, as you mention, at 518192 )
Again, solution is simple: please use the latest offcial release:
